name: CI and Conformance Tests

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  oci-conformance:
    strategy:
      matrix:
        oci-version: [ "stable", "dev" ]
    runs-on: ubuntu-latest
    env:
      # do not automatically upgrade go to a different version: https://go.dev/doc/toolchain
      GOTOOLCHAIN: "local"

    steps:
    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: "Set up Go"
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0

    - name: Build and run olareg in the background
      id: run-olareg
      run: |
        make ci-setup
        echo "port=$(docker port olareg-ci 5000 | head -1 | cut -f2 -d:)" >>$GITHUB_OUTPUT

    - name: Run OCI Distribution Spec Conformance ${{ matrix.oci-version }}
      id: run-conformance
      uses: sudo-bmitch/distribution-spec@pr-conformance-v2
      # uses: opencontainers/distribution-spec@main
      env:
        OCI_VERSION: "${{ matrix.oci-version }}"
        OCI_REGISTRY: "localhost:${{ steps.run-olareg.outputs.port }}"
        OCI_TLS: "disabled"
        OCI_REPO1: "myorg/myrepo"
        OCI_REPO2: "myorg/myrepo2"

    - name: Cleanup
      run: |
        make ci-cleanup

    # TODO: add CI tests with other tools (regclient, crane, skopeo, oras, docker)
