name: Coverage Report

# This setup assumes that you run the unit tests with code coverage in the same
# workflow that will also print the coverage report as comment to the pull request. 
# Therefore, you need to trigger this workflow when a pull request is (re)opened or
# when new code is pushed to the branch of the pull request. In addition, you also
# need to trigger this workflow when new code is pushed to the main branch because 
# we need to upload the code coverage results as artifact for the main branch as
# well since it will be the baseline code coverage.
# 
# We do not want to trigger the workflow for pushes to *any* branch because this
# would trigger our jobs twice on pull requests (once from "push" event and once
# from "pull_request->synchronize")
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'main'

jobs:
  coverage_report:
    name: "Generate coverage report"
    runs-on: ubuntu-latest
    env:
      RELEASE_GO_VER: "1.22"
    permissions:
      pull-requests: write # write permission needed to comment on PR

    steps:
    - name: Checkout repository
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

    - name: Setup Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: "${{ env.RELEASE_GO_VER }}"

    # When you execute your unit tests, make sure to use the "-coverprofile" flag to write a 
    # coverage profile to a file. You will need the name of the file (e.g. "coverage.txt")
    # in the next step as well as the next job.
    - name: Generate coverage
      run: go test -cover -coverprofile=coverage.txt ./...

    - name: Archive code coverage results
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: code-coverage
        path: coverage.txt

    - name: Comment on PR
      if: github.event_name == 'pull_request' # Do not run when workflow is triggered by push to main branch
      uses: fgrosse/go-coverage-report@a284a4c69b3383da62629009e9e8e58976efbf6a # v1.0.0
      continue-on-error: true # This may fail if artifact on main branch does not exist (first run or expired)
      with:
        coverage-artifact-name: "code-coverage"
        coverage-file-name: "coverage.txt"
