name: Docker

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
    tags:
      - 'v*.*.*'
  schedule:
    - cron: '0 06 * * *'

permissions:
  contents: read

jobs:

  docker:
    name: Docker
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed for OIDC Token signing with cosign
      packages: write # needed for pushing packages

    strategy:
      matrix:
        image: ["olareg"]
        type: ["scratch", "alpine"]

    steps:
    - name: Check out code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Prepare
      id: prep
      run: |
        mkdir -p "output/${{matrix.image}}"
        EXT=""
        if [ "${{ matrix.type }}" != "scratch" ]; then
          EXT="-${{ matrix.type }}"
        fi
        HUB_IMAGE=olareg/${{ matrix.image }}
        GHCR_IMAGE=ghcr.io/olareg/${{ matrix.image }}
        VERSION=noop
        if [ "${{ github.event_name }}" = "schedule" ]; then
          VERSION=edge
        elif [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION="${GITHUB_REF#refs/tags/}"
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          VERSION="${GITHUB_REF#refs/heads/}"
          if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
            VERSION=edge
          fi
        elif [[ $GITHUB_REF == refs/pull/* ]]; then
          VERSION="pr-${{ github.event.number }}"
        fi
        VERSION="$(echo "${VERSION}" | sed -r 's#/+#-#g')"
        TAGS="${GHCR_IMAGE}:${VERSION}${EXT}"
        # TAGS="${TAGS},${HUB_IMAGE}:${VERSION}${EXT}"
        if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
          MINOR="${VERSION%.*}"
          MAJOR="${MINOR%.*}"
          # TAGS="${TAGS},${HUB_IMAGE}:${MINOR}${EXT},${HUB_IMAGE}:${MAJOR}${EXT}"
          TAGS="${TAGS},${GHCR_IMAGE}:${MINOR}${EXT},${GHCR_IMAGE}:${MAJOR}${EXT}"
          if [ "${{ matrix.type }}" == "scratch" ]; then
            # TAGS="${TAGS},${HUB_IMAGE}:latest"
            TAGS="${TAGS},${GHCR_IMAGE}:latest"
          else
            # TAGS="${TAGS},${HUB_IMAGE}:${{ matrix.type }}"
            TAGS="${TAGS},${GHCR_IMAGE}:${{ matrix.type }}"
          fi
        fi
        VCS_SEC="$(git log -1 --format=%ct)"
        VCS_DATE="$(date -d "@${VCS_SEC}" +%Y-%m-%dT%H:%M:%SZ --utc)"
        REPO_URL="${{github.server_url}}/${{github.repository}}.git"
        echo "version=${VERSION}" >>$GITHUB_OUTPUT
        echo "image_hub=${HUB_IMAGE}" >>$GITHUB_OUTPUT
        echo "image_ghcr=${GHCR_IMAGE}" >>$GITHUB_OUTPUT
        echo "tags=${TAGS}" >>$GITHUB_OUTPUT
        echo "vcs_sec=${VCS_SEC}" >>$GITHUB_OUTPUT
        echo "created=${VCS_DATE}" >>$GITHUB_OUTPUT
        echo "repo_url=${REPO_URL}" >>$GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

    # - name: Login to DockerHub
    #   if: github.repository_owner == 'olareg'
    #   uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0 
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GHCR
      if: github.repository_owner == 'olareg'
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
      id: build
      with:
        context: .
        file: ./build/Dockerfile.${{ matrix.image }}.buildkit
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        target: release-${{ matrix.type }}
        outputs: type=oci,dest=output/${{matrix.image}}-${{matrix.type}}.tar
        build-args: |
          SOURCE_DATE_EPOCH=${{ steps.prep.outputs.vcs_sec }}
        labels: |
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.source=${{ steps.prep.outputs.repo_url }}
          org.opencontainers.image.version=${{ steps.prep.outputs.version }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Install cosign
      if: github.event_name != 'pull_request' && github.repository_owner == 'olareg'
      uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4 # v3.4.0
      with:
        cosign-release: "v2.2.3"
    
    - name: Install syft
      if: github.event_name != 'pull_request' && github.repository_owner == 'olareg'
      uses: anchore/sbom-action/download-syft@b6a39da80722a2cb0ef5d197531764a89b5d48c3 # v0.15.8
      id: syft
      with:
        syft-version: "v0.103.1"
    
    # Use regctl to modify olareg images to improve reproducibility
    - name: Install regctl
      uses: regclient/actions/regctl-installer@36cf95c1ea691643b8e8aad3d10b8b8658fad984 # main
      if: github.event_name != 'pull_request' && github.repository_owner == 'olareg'

    - name: Mutate
      if: github.event_name != 'pull_request' && github.repository_owner == 'olareg'
      id: mutate
      run: |
        vcs_date="${{ steps.prep.outputs.created }}"
        base_name=""
        mkdir -p "output/${{matrix.image}}"
        if [ "${{matrix.type}}" = "alpine" ]; then
          base_name="alpine:3"
          base_digest="$(regctl image digest "${base_name}")"
        fi
        # mutate the image locally
        local_tag="ocidir://output/${{matrix.image}}:${{matrix.type}}"
        echo "Loading ${local_tag} from output/${{matrix.image}}-${{matrix.type}}.tar"
        regctl image import "${local_tag}" "output/${{matrix.image}}-${{matrix.type}}.tar"
        echo "Modifying image for reproducibility"
        regctl image mod "${local_tag}" --replace \
          --to-oci-referrers
        regctl image mod "${local_tag}" --replace \
          --annotation "[*]org.opencontainers.image.created=${vcs_date}" \
          --annotation "[*]org.opencontainers.image.source=${{ steps.prep.outputs.repo_url }}" \
          --annotation "[*]org.opencontainers.image.version=${{ steps.prep.outputs.version }}" \
          --annotation "[*]org.opencontainers.image.revision=${{ github.sha }}"
        if [ -n "$base_name" ] && [ -n "$base_digest" ]; then
          regctl image mod "${local_tag}" --replace \
            --annotation "[*]org.opencontainers.image.base.name=${base_name}" \
            --annotation "[*]org.opencontainers.image.base.digest=${base_digest}" \
            --reproducible \
            --time "set=${vcs_date},base-ref=${base_name}@${base_digest}"
        else
          regctl image mod "${local_tag}" --replace \
            --reproducible \
            --time "set=${vcs_date}"
        fi
        echo "digest=$(regctl image digest ${local_tag})" >>$GITHUB_OUTPUT

    - name: Attach SBOMs
      if: github.event_name != 'pull_request' && github.repository_owner == 'olareg'
      id: sbom
      run: |
        now_date="$(date +%Y-%m-%dT%H:%M:%SZ --utc)"
        for digest in $(regctl manifest get ocidir://output/${{matrix.image}}:${{matrix.type}} \
                        --format '{{range .Manifests}}{{printf "%s\n" .Digest}}{{end}}'); do
          echo "Attaching SBOMs for ${{matrix.image}}@${digest}"
          regctl image copy ocidir://output/${{matrix.image}}@${digest} ocidir://output/${{matrix.image}}-sbom -v warn >/dev/null
          ${{steps.syft.outputs.cmd}} packages -q "oci-dir:output/${{matrix.image}}-sbom" \
              --source-name "docker:docker.io/olareg/${{matrix.image}}@${digest}" -o cyclonedx-json \
            | regctl artifact put --subject "ocidir://output/${{matrix.image}}@${digest}" \
                --artifact-type application/vnd.cyclonedx+json \
                -m application/vnd.cyclonedx+json \
                --annotation "org.opencontainers.image.created=${now_date}" \
                --annotation "org.opencontainers.image.description=CycloneDX JSON SBOM"
          ${{steps.syft.outputs.cmd}} packages -q "oci-dir:output/${{matrix.image}}-sbom" \
              --source-name "docker:docker.io/olareg/${{matrix.image}}@${digest}" -o spdx-json \
            | regctl artifact put --subject "ocidir://output/${{matrix.image}}@${digest}" \
                --artifact-type application/spdx+json \
                -m application/spdx+json \
                --annotation "org.opencontainers.image.created=${now_date}" \
                --annotation "org.opencontainers.image.description=SPDX JSON SBOM"
          rm -r output/${{matrix.image}}-sbom
        done

    - name: Push and Sign
      if: github.event_name != 'pull_request' && github.repository_owner == 'olareg'
      id: push
      run: |
        # loop over the tags
        image_hub="${{ steps.prep.outputs.image_hub }}"
        for tag in $(echo ${{ steps.prep.outputs.tags }} | tr , ' '); do
          digest="$(regctl image digest "ocidir://output/${{matrix.image}}:${{matrix.type}}")"
          if [ "${digest}" = "$(regctl image digest "${tag}" 2>/dev/null || true)" ]; then
            # image already pushed, don't add referrers to reproducible builds
            echo "Skipping ${tag}"
          else
            echo "Pushing ${tag}"
            regctl image copy --referrers "ocidir://output/${{matrix.image}}:${{matrix.type}}@${digest}" "${tag}"
            cosign sign -y -r "${tag}@${digest}"
          fi
        done
