name: Release

on:
  push:
    branches: [ "main" ]
    paths: [ "RELEASE.md" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-tags: true
        persist-credentials: true

    - name: Tag release
      id: tag_release
      env:
        RELEASE_FILE: RELEASE.md
        TMP_FILE: /tmp/RELEASE.md
        RELEASE_PREFIX: "## Release "
      run: |
        # parse file to get the tag, and write current release notes to a temp file
        awk "/^${RELEASE_PREFIX}/{if(++c>1)exit} c==1" <"${RELEASE_FILE}" >"${TMP_FILE}"
        TAG="$(grep "${RELEASE_PREFIX}" "${TMP_FILE}")"
        TAG="${TAG#${RELEASE_PREFIX}}"
        # validate tag syntax
        if [[ ! $TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.*|$) ]]; then
          echo "Unexpected tag syntax: \"${TAG}\"" >&2
          exit 1
        fi
        # verify git tag is not already used
        if git show "refs/tags/${TAG}" >/dev/null 2>&1; then
          echo "Tag \"${TAG}\" already exists" >&2
          exit 1
        fi
        # impersonate the last committer
        if ! git config get user.name >/dev/null 2>&1 || ! git config get user.email >/dev/null 2>&1; then
          git config set user.email "$(git log -q --format=format:%ae)"
          git config set user.name "$(git log -q --format=format:%an)"
        fi
        # run git tag for requested tag
        git tag -am "${TAG}" "${TAG}"
        # for non-rc releases, compute and force create major and minor tags
        if [[ $TAG =~ [0-9\.]+-.+$ ]]; then
          # prerelease
        else
          # stable release
          TAG_MINOR="${TAG%.*}"
          TAG_MAJOR="${TAG_MINOR%.*}"
          git tag -afm "${TAG_MINOR}" "${TAG_MINOR}"
          git tag -afm "${TAG_MAJOR}" "${TAG_MAJOR}"
        fi
        # push all tags
        git push origin --tags --force

    # The go.yml and docker.yml workflows will pickup the pushed tag and generate a release
