name: Version Check

on:
  schedule:
    - cron: '0 05 * * 0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Version Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Version Check
        uses: docker://ghcr.io/sudo-bmitch/version-bump:edge
        with:
          args: check
