name: Vulnerability Scans

on:
  schedule:
    - cron: '0 06 * * 0' # 6am UTC on Sundays
  workflow_dispatch:

permissions:
  contents: read

jobs:
  govunlcheck:
    name: Go Vuln Check
    runs-on: ubuntu-latest
    env:
      RELEASE_GO_VER: "1.21"

    steps:
    - name: Check out code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: "Set up Go"
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: "${{ env.RELEASE_GO_VER }}"
        check-latest: true

    - name: "Install govulncheck"
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: "Run govulncheck"
      run: |
        govulncheck ./...

    - name: "Install OSV Scanner"
      run: |
        go install github.com/google/osv-scanner/cmd/osv-scanner@latest

    - name: "Run OSV Scanner"
      run: |
        osv-scanner -r .
